#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Production Level 2 trading strategy.

Level 2 = Level 1 + deterministic volatility response.

Inherited Level 1 core
-----------------------
    30-day regime detector
    Bullish -> 10-day DCA
    Neutral -> 14-day DCA
    Bearish -> 21-day DCA
    Rolling 30-day capital-deployment safeguard

Frozen Level 2 parameters
--------------------------
    Downside trigger: -4% daily move
    Downside response: double the NEXT regime-scheduled DCA
    Upside trigger: +5% daily move
    Upside sale: 15% of the gain from the day's uptick

There is NO normal profit-taking mechanism in production Level 2.
DCA frequency is inherited from Level 1 and is not user-configurable.
"""

from Apziva_Trading_Strategy_Level1 import TradingStrategyLevel1


class TradingStrategyLevel2(TradingStrategyLevel1):
    """Level 1 regime-adaptive accumulation plus volatility behaviour."""

    risk_level = 2

    DOWNSIDE_TRIGGER_PCT = 4.0
    DOWNSIDE_DCA_MULTIPLIER = 2.0
    UPSIDE_TRIGGER_PCT = 5.0
    UPSIDE_SELL_FRACTION_PCT = 15.0

    def __init__(self, budget, dca_amount, **level1_kwargs):
        super().__init__(budget=budget, dca_amount=dca_amount, **level1_kwargs)

        self.next_dca_multiplier = 1.0
        self.downside_trigger_count = 0
        self.upside_trigger_count = 0
        self.last_trigger_day = None

    @staticmethod
    def calculate_daily_move_pct(previous_price, current_price):
        if previous_price is None or previous_price <= 0:
            return 0.0
        return ((current_price - previous_price) / previous_price) * 100.0

    def update_level2_triggers(self, previous_price, current_price, day):
        result = {
            "daily_move_pct": 0.0,
            "downside_triggered": False,
            "upside_triggered": False,
        }

        if previous_price is None or previous_price <= 0 or current_price <= 0:
            return result

        if self.last_trigger_day is not None and day.date() == self.last_trigger_day.date():
            return result

        move_pct = self.calculate_daily_move_pct(previous_price, current_price)
        result["daily_move_pct"] = move_pct
        self.last_trigger_day = day

        if move_pct <= -self.DOWNSIDE_TRIGGER_PCT:
            self.next_dca_multiplier = max(
                self.next_dca_multiplier,
                self.DOWNSIDE_DCA_MULTIPLIER,
            )
            self.downside_trigger_count += 1
            result["downside_triggered"] = True

        if move_pct >= self.UPSIDE_TRIGGER_PCT:
            self.upside_trigger_count += 1
            result["upside_triggered"] = True

        return result

    def calculate_level2_upside_sale(self, previous_price, current_price):
        """Calculate the opportunistic sale generated by a +5% daily uptick."""
        if self.btc_held <= 0:
            return 0.0
        if previous_price is None or previous_price <= 0 or current_price <= 0:
            return 0.0

        daily_move_pct = self.calculate_daily_move_pct(previous_price, current_price)
        if daily_move_pct < self.UPSIDE_TRIGGER_PCT:
            return 0.0

        uptick_gain = self.btc_held * (current_price - previous_price)
        target_sale_value = uptick_gain * (self.UPSIDE_SELL_FRACTION_PCT / 100.0)
        btc_to_sell = target_sale_value / current_price
        return min(btc_to_sell, self.btc_held)

    def execute_sale(self, btc_to_sell, price):
        """Sell BTC and allocate cost basis proportionally."""
        if btc_to_sell <= 0 or self.btc_held <= 0:
            return 0.0

        btc_to_sell = min(btc_to_sell, self.btc_held)
        cost_basis_sold = self.btc_cost_basis * (btc_to_sell / self.btc_held)
        sale_proceeds = btc_to_sell * price
        realised_profit = sale_proceeds - cost_basis_sold

        self.btc_held -= btc_to_sell
        self.btc_cost_basis -= cost_basis_sold
        self.cash += sale_proceeds
        return realised_profit

    def make_decision(self, data, previous_price=None):
        day = data["Timestep"].iloc[-1]
        price = float(data["Close"].iloc[-1])

        self.update_regime(data)
        portfolio_value = self.portfolio_value(price)
        stop_status = self.update_global_stop(day, portfolio_value)
        self.record_portfolio_value(data)

        if not self.trading_enabled:
            return {
                "action": "HOLD", "amount": 0.0, "price": price,
                "Timestep": day, "reason": "Trading disabled",
            }

        if stop_status["active"]:
            return {
                "action": "HOLD", "amount": 0.0, "price": price,
                "Timestep": day, "reason": "Global drawdown safeguard active",
            }

        trigger_result = self.update_level2_triggers(previous_price, price, day)

        if self.last_dca_day is not None and day.date() == self.last_dca_day.date():
            return {
                "action": "HOLD", "amount": 0.0, "price": price,
                "Timestep": day, "reason": "DCA already executed today",
                "trigger_result": trigger_result,
            }

        # The +5% response is opportunistic and independent of scheduled DCA.
        upside_btc_to_sell = 0.0
        if trigger_result["upside_triggered"]:
            upside_btc_to_sell = self.calculate_level2_upside_sale(previous_price, price)

        if upside_btc_to_sell > 0:
            return {
                "action": "SELL",
                "amount": upside_btc_to_sell,
                "normal_amount": 0.0,
                "upside_amount": upside_btc_to_sell,
                "price": price,
                "Timestep": day,
                "reason": "Level 2 upside response",
                "trigger_result": trigger_result,
            }

        base_dca_amount = self.calculate_dca(day)
        if base_dca_amount <= 0:
            return {
                "action": "HOLD", "amount": 0.0, "price": price,
                "Timestep": day, "reason": "DCA not scheduled",
                "trigger_result": trigger_result,
                "regime": self.current_regime,
                "dca_frequency_days": self.current_dca_frequency,
            }

        dca_amount = base_dca_amount * self.next_dca_multiplier
        if self.cash <= 0:
            return {
                "action": "HOLD", "amount": 0.0, "price": price,
                "Timestep": day, "reason": "DCA scheduled but no cash available",
                "trigger_result": trigger_result,
            }

        return {
            "action": "BUY",
            "amount": min(dca_amount, self.cash),
            "price": price,
            "Timestep": day,
            "reason": "Level 2 regime-adaptive DCA",
            "dca_multiplier": self.next_dca_multiplier,
            "trigger_result": trigger_result,
            "regime": self.current_regime,
            "regime_return_pct": self.current_regime_return_pct,
            "dca_frequency_days": self.current_dca_frequency,
        }

    def execute_decision(self, decision):
        action = decision.get("action")

        if action == "BUY":
            btc_bought = self.buy(decision["amount"], decision["price"])
            if btc_bought > 0:
                self.last_dca_day = decision["Timestep"]
                self.next_dca_multiplier = 1.0
            return btc_bought

        if action == "SELL":
            return self.execute_sale(
                decision.get("upside_amount", decision["amount"]),
                decision["price"],
            )

        return 0.0
